---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: petstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petstore
    spec:
      initContainers:
        - name: init-networking
          image: kubeshop/openapi-sidecar-init:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          env:
            - name: SOURCE_PORT
              value: "8080"
            - name: DEST_PORT
              value: "8000"
      containers:
        - name: service
          image: swaggerapi/petstore3:unstable
          ports:
            - containerPort: 8080
        - name: proxy
          image: kubeshop/openapi-sidecar:latest
          ports:
            - containerPort: 8000
          env:
            - name: PROXY_PORT
              value: "8000"
            - name: SERVICE_PORT
              value: "8080"
            - name: OPENAPI_PATH
              value: "/api/v3/openapi.json"